### ISSUE TITLE
terraform crashes when using the rancher2_cluster data object. 

### ISSUE THREAD

**Issue by aschepp** [rancher/terraform-provider-rancher2#119]
Hello,

we setup a rke cluster on rancheros/vsphere and installed rancher 2.2.8 on it. When trying to use the following terraform code, terraform crashes every time.

```
data "rancher2_cluster" "local" {
  name = "local"
}
```

See the following crash log for more information:

```
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: panic: runtime error: invalid memory address or nil pointer dereference
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf11adc]
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: goroutine 30 [running]:
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/rancher2.flattenCluster(0xc0001481c0, 0xc000171180, 0xc00080b080, 0xc00057f620, 0xc0009dcdd0, 0xd, 0xc0009dcba0, 0xd, 0x0, 0xc00057f620)
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/rancher2/structure_cluster.go:76 +0x3ec
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/rancher2.resourceRancher2ClusterRead(0xc0001481c0, 0x1238120, 0xc000474f80, 0x0, 0x0)
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/rancher2/resource_rancher2_cluster.go:121 +0x4d0
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/rancher2.dataSourceRancher2ClusterRead(0xc0001481c0, 0x1238120, 0xc000474f80, 0xc0001481c0, 0x0)
2019-08-29T18:17:42.386+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/rancher2/data_source_rancher2_cluster.go:141 +0x376
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).ReadDataApply(0xc00044b580, 0xc0003dc2e0, 0x1238120, 0xc000474f80, 0xc000466928, 0x1, 0x0)
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:390 +0x88
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).ReadDataApply(0xc000474800, 0xc000207b18, 0xc0003dc2e0, 0xc0003dc2e0, 0x0, 0x0)
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:442 +0x17f
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadDataSource(0xc00000e598, 0x14b9840, 0xc0001d7aa0, 0xc000264900, 0xc00000e598, 0x32, 0xc000577bd0)
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:990 +0x45f
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadDataSource_Handler(0x11f29a0, 0xc00000e598, 0x14b9840, 0xc0001d7aa0, 0xc00023e000, 0x0, 0x14b9840, 0xc0001d7aa0, 0xc0000a69a0, 0x147)
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3055 +0x23e
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc000001c80, 0x14c70a0, 0xc0003b6480, 0xc00015b000, 0xc000130e10, 0x1ece590, 0x0, 0x0, 0x0)
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/vendor/google.golang.org/grpc/server.go:966 +0x470
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/vendor/google.golang.org/grpc.(*Server).handleStream(0xc000001c80, 0x14c70a0, 0xc0003b6480, 0xc00015b000, 0x0)
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/vendor/google.golang.org/grpc/server.go:1245 +0xd25
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: github.com/terraform-providers/terraform-provider-rancher2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003ce630, 0xc000001c80, 0x14c70a0, 0xc0003b6480, 0xc00015b000)
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/vendor/google.golang.org/grpc/server.go:685 +0x9f
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: created by github.com/terraform-providers/terraform-provider-rancher2/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
2019-08-29T18:17:42.387+0200 [DEBUG] plugin.terraform-provider-rancher2_v1.4.1_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-rancher2/vendor/google.golang.org/grpc/server.go:683 +0xa1
2019-08-29T18:17:42.389+0200 [DEBUG] plugin: plugin process exited: path=/redacted/.terraform/plugins/linux_amd64/terraform-provider-rancher2_v1.4.1_x4 pid=28014 error="exit status 2"
2019/08/29 18:17:42 [ERROR] <root>: eval: *terraform.EvalReadData, err: rpc error: code = Unavailable desc = transport is closing
2019/08/29 18:17:42 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2019/08/29 18:17:42 [TRACE] [walkRefresh] Exiting eval tree: data.rancher2_cluster.local
2019/08/29 18:17:42 [TRACE] vertex "data.rancher2_cluster.local": visit complete
2019/08/29 18:17:42 [TRACE] vertex "data.rancher2_cluster.local": dynamic subgraph encountered errors
2019/08/29 18:17:42 [TRACE] vertex "data.rancher2_cluster.local": visit complete
```

**Comment by rawmind0** [comment]
Hi @aschepp,

it's weird, in my v2.2.8 system the datasource is working fine. Is your rancher system upgraded from previous stable or rc version or brand new v2.2.8?? Could you please take a look at API for `https://<RANCHER_URL>/v3/clusters/local` and check it `enableNetworkPolicy` field exists??

**Comment by aschepp** [comment]
Yes, it doesn't exist, it returns null in the API.

**Comment by rawmind0** [comment]
Is your rancher system upgraded from previous stable or rc version or it's a brand new v2.2.8?? 

PR #122 submitted to address issue.

**Comment by aschepp** [comment]
It was a brand new cluster, setup using terraform. First setup of rke with rke_cluster then install helm, then install rancher with helm, then rancher2_bootstrap.

**Comment by rawmind0** [comment]
Merged PR to address this issue. Please, reopen if needed.
