### ISSUE TITLE
rancher provider 1.13.0 fails with azure after upgrade from 1.11.0

### ISSUE THREAD

**Issue by lkjangir** [rancher/terraform-provider-rancher2#615]
As soon as  I changed upgraded rancher provider to 1.13.0, it started failing with azure. 

Error: Error building ARM Config: obtain subscription() from Azure CLI: Error parsing json result from the Azure CLI: Error retrieving running Azure CLI: --- Logging error ---
Traceback (most recent call last):
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 60, in <module>
    raise ex
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 53, in <module>
    sys.exit(exit_code)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/handlers.py", line 70, in emit
    self.doRollover()
  File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/handlers.py", line 171, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/logging/handlers.py", line 111, in rotate
    os.rename(source, dest)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lokesh.jangir/.azure/telemetry/cache' -> '/Users/lokesh.jangir/.azure/telemetry/cache.1'
Call stack:
  File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.8/3.8.7_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/__main__.py", line 123, in <module>
    telemetry.conclude()
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 240, in _wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/decorators.py", line 74, in _wrapped_func
    return func(*args, **kwargs)
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/core/telemetry.py", line 296, in conclude
    save(get_config_dir(), _session.generate_payload())
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/telemetry/__init__.py", line 51, in save
    if save_payload(config_dir, payload) and should_upload(config_dir):
  File "/usr/local/Cellar/azure-cli/2.19.1/libexec/lib/python3.8/site-packages/azure/cli/telemetry/util.py", line 53, in save_payload
    cache_saver.info(payload)
Message: '{"c4395b75-49cc-422c-bc95-c7d51aef5d46":[{"name":"azurecli/command","properties":{"Reserved.DataModel.EntityType":"UserTask","Reserved.DataModel.Action.Type":"Atomic","Reserved.DataModel.Action.Result":"Success","Reserved.ChannelUsed":"AI","Reserved.EventId":"47793204-2df3-479e-8cd3-deff78999d02","Reserved.SequenceNumber":1,"Reserved.SessionId":"bd7a1a5b8037c7f90942a9aea1d9116c4e0bd0b745211388562fc70c6c42b940","Reserved.TimeSinceSessionStart":0,"Reserved.DataModel.Source":"DataModelAPI","Reserved.DataModel.EntitySchemaVersion":4,"Reserved.DataModel.Severity":0,"Reserved.DataModel.ProductName":"azurecli","Reserved.DataModel.FeatureName":"command","Reserved.DataModel.EntityName":"account-show","Reserved.DataModel.CorrelationId":"fa3b71fd-6de9-4725-b2ae-90eea9f7d8b5","Context.Default.VS.Core.ExeName":"azurecli","Context.Default.VS.Core.ExeVersion":"2.19.1@none","Context.Default.VS.Core.MacAddressHash":"7b164ec774aa1da536fd2397f47708f2c4f18270b79d9d92e569f233a42a7ee6","Context.Default.VS.Core.Machine.Id":"7b164ec7-74aa-1da5-36fd-2397f47708f2","Context.Default.VS.Core.OS.Type":"darwin","Context.Default.VS.Core.OS.Version":"darwin kernel version 19.6.0: thu jun 18 20:49:00 pdt 2020; root:xnu-6153.141.1~1/release_x86_64","Context.Default.VS.Core.OS.Platform":"macos-10.15.6-x86_64-i386-64bit","Context.Default.VS.Core.User.Id":"18ab3576-48c9-11eb-adef-a683e746d7cc","Context.Default.VS.Core.User.IsMicrosoftInternal":"False","Context.Default.VS.Core.User.IsOptedIn":"True","Context.Default.VS.Core.TelemetryApi.ProductVersion":"azurecli@2.19.1","Context.Default.AzureCLI.Source":"az","Context.Default.AzureCLI.ClientRequestId":"daaae2f8-949f-11eb-9a02-acde48001122","Context.Default.AzureCLI.CoreVersion":"2.19.1","Context.Default.AzureCLI.TelemetryVersion":"2.0","Context.Default.AzureCLI.InstallationId":"18ab3576-48c9-11eb-adef-a683e746d7cc","Context.Default.AzureCLI.ShellType":"/bin/bash","Context.Default.AzureCLI.UserAzureId":"d43258e5a00924b84e257c7caccc3f57afebcd049c9c08f22fd386e8d64374fa","Context.Default.AzureCLI.UserAzureSubscriptionId":"f21d530c-24dd-42f5-b603-02a2c5c1281c","Context.Default.AzureCLI.DefaultOutputType":"unknown","Context.Default.AzureCLI.EnvironmentVariables":"[]","Context.Default.AzureCLI.Locale":"None,UTF-8","Context.Default.AzureCLI.StartTime":"2021-04-03 17:13:05.405089","Context.Default.AzureCLI.EndTime":"2021-04-03 17:13:05.452352","Context.Default.AzureCLI.InitTimeElapsed":"0.112813","Context.Default.AzureCLI.InvokeTimeElapsed":"0.041495","Context.Default.AzureCLI.OutputType":"json","Context.Default.AzureCLI.RawCommand":"account show","Context.Default.AzureCLI.Params":"-o","Context.Default.AzureCLI.PythonVersion":"3.8.7","Context.Default.AzureCLI.Mode":"default","Context.Default.AzureCLI.Installer":"HOMEBREW","Context.Default.AzureCLI.error_type":"None","Context.Default.AzureCLI.exception_name":"None","Context.Default.AzureCLI.debug_info":"","Context.Default.AzureCLI.PollStartTime":"None","Context.Default.AzureCLI.PollEndTime":"None"}}]}'
Arguments: ()

**Comment by rawmind0** [comment]
@lkjangir , not understanding what these python error logs means. I can't see anything related with the rancher2 provider (coded in golang). Could you please clarify and provide more info and context??
