### ISSUE TITLE
The terraform-provider-rancher2_v1.20.0 plugin crashed!

### ISSUE THREAD

**Issue by mmclane** [rancher/terraform-provider-rancher2#790]
When I run terraform apply I get the following output
```
rancher2_cluster.imported: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with rancher2_cluster.imported,
│   on 05_rancher_bootstrap.tf line 17, in resource "rancher2_cluster" "imported":
│   17: resource "rancher2_cluster" "imported" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-rancher2_v1.20.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ba0869]

goroutine 80 [running]:
github.com/terraform-providers/terraform-provider-rancher2/rancher2.expandClusterEKSConfigV2(0xc000d243f0, 0x1, 0x1, 0x4)
        /go/src/github.com/rancher/terraform-provider-rancher2/rancher2/structure_cluster_eks_config_v2.go:290 +0x369
github.com/terraform-providers/terraform-provider-rancher2/rancher2.expandCluster(0xc0004385b0, 0xc00114c000, 0x0, 0x0)
        /go/src/github.com/rancher/terraform-provider-rancher2/rancher2/structure_cluster.go:510 +0x94a
github.com/terraform-providers/terraform-provider-rancher2/rancher2.resourceRancher2ClusterCreate(0xc0004385b0, 0x210e2c0, 0xc0000f8300, 0x0, 0x0)
        /go/src/github.com/rancher/terraform-provider-rancher2/rancher2/resource_rancher2_cluster.go:123 +0xae
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc000257680, 0xc000b64f50, 0xc000f7c9c0, 0x210e2c0, 0xc0000f8300, 0x1e25e01, 0xc000ac7d28, 0xc0001c1650)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:310 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0008ce000, 0xc0001e3a38, 0xc000b64f50, 0xc000f7c9c0, 0xc001148aa8, 0xc000f2f700, 0x1e290a0)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000223518, 0x24794f0, 0xc000dda4e0, 0xc0004390a0, 0xc000223518, 0xc000dda4e0, 0xc0005b3ba0)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x2045aa0, 0xc000223518, 0x24794f0, 0xc000dda4e0, 0xc000e684e0, 0x0, 0x24794f0, 0xc000dda4e0, 0xc0000f6400, 0x8f6)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008dc380, 0x24904d8, 0xc000642900, 0xc0001ccd00, 0xc00082e990, 0x32b7d60, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0008dc380, 0x24904d8, 0xc000642900, 0xc0001ccd00, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000220550, 0xc0008dc380, 0x24904d8, 0xc000642900, 0xc0001ccd00)
        /go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd

Error: The terraform-provider-rancher2_v1.20.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

The following in my terraform config that causes this.  In this config I am trying to connect to my rancher2 server and import this newly created EKS cluster.

```hcl
locals {
  rancher_url = var.rancher_url == "" ? "rancher.hub.${var.dns_domain}" : var.rancher_url
}
provider "rancher2" {
  alias     = "admin"
  bootstrap = false
  api_url   = "https://${local.rancher_url}:8443/v3"
  token_key = var.rancher_token
  insecure = true
}

data "rancher2_cloud_credential" "cred" {
  name     = var.rancher_cloud_creds
  provider = rancher2.admin
}
resource "rancher2_cluster" "imported" {
  name        = local.cluster_name
  description = "${local.cluster_name} cluster"
  provider    = rancher2.admin
  eks_config_v2 {
    cloud_credential_id = data.rancher2_cloud_credential.cred.id
    region              = var.region
    imported            = true
  }
}
```

So far I have not done any troubleshooting of my own but the error message said it was a bug and asked that I report it.

**Comment by rawmind0** [comment]
This was addressed on provider version 1.20.1 https://github.com/rancher/terraform-provider-rancher2/issues/753
