### ISSUE TITLE
Plugin crashed after terraform apply

### ISSUE THREAD

**Issue by empeekdev** [rancher/terraform-provider-rancher2#839]
Hi, we are trying to configure OKTA authentication and after `terraform apply` we encountered with the following error.
 
We had the similar problem with terraform-provider-rancher2 v1.21.0

```
Stack trace from the terraform-provider-rancher2_v1.22.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1a3e3db]

goroutine 92 [running]:
github.com/rancher/norman/clientbase.(*APIOperations).DoByID(0x0, 0x2de52d4, 0x7, 0x2deb29a, 0xb, 0x29a6be0, 0xc0007b0000, 0x315dbf8, 0xc000c582a0)
        /go/pkg/mod/github.com/rancher/norman@v0.0.0-20211201154850-abe17976423e/clientbase/ops.go:251 +0x9b
github.com/rancher/rancher/pkg/client/generated/management/v3.(*SettingClient).ByID(0xc000286cf8, 0x2deb29a, 0xb, 0x315dbf8, 0xc000c582a0, 0xc000c64640)
        /go/pkg/mod/github.com/rancher/rancher/pkg/client@v0.0.0-20211218171736-3c1d5fac3248/generated/management/v3/zz_generated_setting.go:120 +0x89
github.com/rancher/terraform-provider-rancher2/rancher2.(*Config).getK8SDefaultVersion(0xc000e4a180, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/terraform-provider-rancher2/rancher2/config.go:135 +0xfe
github.com/rancher/terraform-provider-rancher2/rancher2.(*Config).ManagementClient(0xc000e4a180, 0x0, 0x0, 0x0)
        /go/src/github.com/rancher/terraform-provider-rancher2/rancher2/config.go:285 +0x1d2
github.com/rancher/terraform-provider-rancher2/rancher2.resourceRancher2AuthConfigOKTACreate(0xc000e18b60, 0x2ddbd00, 0xc000e4a180, 0x2, 0x404c2e0)
        /go/src/github.com/rancher/terraform-provider-rancher2/rancher2/resource_rancher2_auth_config_okta.go:23 +0x5a
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0001665a0, 0xc000dfeaf0, 0xc000dc44c0, 0x2ddbd00, 0xc000e4a180, 0x2ad9801, 0xc000d92608, 0xc000e1b410)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/resource.go:310 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0005a0000, 0xc000d5ba38, 0xc000dfeaf0, 0xc000dc44c0, 0xc000d92410, 0xc00000e1c0, 0x2adccc0)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-p╷
│ Error: Plugin did not respond
│ 
│   with module.rancher.rancher2_auth_config_okta.okta,
│   on rancher-server/rancher.tf line 72, in resource "rancher2_auth_config_okta" "okta":
│   72: resource "rancher2_auth_config_okta" "okta" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
lugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000286240, 0x315dc30, 0xc000c61980, 0xc000e185b0, 0xc000286240, 0xc000c61980, 0xc000da4ba0)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x2d105a0, 0xc000286240, 0x315dc30, 0xc000c61980, 0xc000dc8360, 0x0, 0x315dc30, 0xc000c61980, 0xc000d29000, 0x4335)
        /go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022ea80, 0x3175938, 0xc000683800, 0xc000c9afc0, 0xc000c44cf0, 0x40004c0, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1297 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00022ea80, 0x3175938, 0xc000683800, 0xc000c9afc0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:1626 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00005a240, 0xc00022ea80, 0x3175938, 0xc000683800, 0xc000c9afc0)
        /go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:941 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.40.0/server.go:939 +0x1fd

Error: The terraform-provider-rancher2_v1.22.2 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

The code that cause this problem

```
resource "rancher2_auth_config_okta" "okta" {
  provider = rancher2.admin
  display_name_field = "FirstName"
  groups_field = "memberOf"
  idp_metadata_content = file("${path.module}/Rancher_SSO_metadata.xml")
  rancher_api_host = "https://foo.bar"
  sp_cert = file("${path.module}/rancher-sso.cert")
  sp_key = file("${path.module}/rancher-sso.key")
  uid_field = "Name"
  user_name_field = "Subject"
}
```

Terraform version:
```
terraform --version


Terraform v1.0.11
on darwin_amd64
```

terraform-provider-rancher2 version: `v1.22.2`

**Comment by matttrach** [comment]
This issue is a couple of years old now and can only reference unsupported versions, so I am going to close it, feel free to open a new issue if this is still an problem.
